name: The Identity Platform for Developers
title: Okta Developer
email: developers@okta.com
description: > # this means to ignore newlines until "baseurl:"
  Secure, scalable, and highly available authentication and user management for any app.
baseurl: ""
url: "https://developer.okta.com"
twitter_username: OktaDev
github_username:  oktadeveloper
disqus_shortname: oktadevblog

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-assets
  - jekyll-include-cache
  - jekyll-asciidoc
  - asciidoctor-rouge

source: _source
destination: dist

markdown: kramdown
markdown_ext: md

kramdown:
  syntax_highlighter: rouge
  toc_levels: 1..3

permalink: /blog/:year/:month/:day/:title

support_phone_number: "1-888-722-7871"
github_base_url: "https://github.com/okta/okta.github.io/tree/source/_source/"
github_edit_url: "https://github.com/okta/okta.github.io/edit/source/_source/"
get_started_url: "https://developer.okta.com/signup/"
stack_overflow_forum_url: "http://stackoverflow.com/search?q=okta"

timezone: EST
ga_ua_id: "UA-15777010-3"

# This is different from "url"
# This variable will prevent user from committing sitemap with local url
production_url: "https://developer.okta.com"

include: [_static, .nojekyll, .woff, .tff]

assets:
  compress:
    css: true
    js:  true
  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  features:
    liquid: false
    integrity: false
    automatic_img_size: false
    automatic_img_alt : true

collections:
  standards:
    output: true
  code:
    output: true
  use_cases:
    output: true
  authentication-guide:
    output: true
  reference:
    output: true
  3rd_party_notices:
    output: true
  docs:
    output: true
  quickstarts:
    output: true
  change-log:
    output: true
    permalink: /docs/change-log/
  sdk:
    output: true
    permalink: /docs/sdk/:path

paginate: 10
paginate_path: "/blog/page/:num"

defaults:
  -
    scope:
      collection: code
    values:
      layout: software
  -
    scope:
      collection: reference
    values:
      layout: documentation
  -
    scope:
      collection: docs
    values:
      toc: true
  - 
    scope:
      collection: use_cases
    values:
      hidden: false

sitemap_ignore:
  - sdk
  - change-log
  - quickstart-fragments
  - 3rd_party_notices
  # Omit from sitemap.collection traversal
  - posts

# Okta Library versions
versions:
  jwt_validator_java: 0.2.0
  spring_boot_starter: 0.5.0
  okta_signin_widget: 2.6.0

# Bug: 37458
# Add Discourse link
dev_forum:  https://devforum.okta.com/


# Location of main Drupal site for navigation and shared resources
external_domain: https://developer.okta.com

# Link for telling people to contact support

contact_support_lc: contact <a href="https://support.okta.com/help/open_case" target="_blank">Support</a>
contact_support_uc: Contact <a href="https://support.okta.com/help/open_case" target="_blank">Support</a>

# AsciiDoc settings - only applies to blog. Can be removed when we move to Hugo for the blog.
asciidoctor:
  attributes:
    source-highlighter: rouge
    icons: font
  base_dir: :_source
