# name: '[dev.okta] build and checks'

# on: pull_request

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       NODE_OPTIONS: '--max_old_space_size=3584'

#     strategy:
#       matrix:
#         node-version: [14.x]

#     steps:
#     - name: Checkout repository!
#       uses: actions/checkout@v3
#     - name: Setup node - ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - name: Install dependencies
#       run: yarn install --frozen-lockfile
#     - name: Build
#       run: yarn build
#     - name: Run checks
#       run: ./scripts/yarn-checks.sh
#       shell: bash
